// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "UserData.pb.h"

@implementation UserDataRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [UserDataRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface User_Info ()
@property (retain) NSString* username;
@property (retain) NSString* nickName;
@property int32_t birthday;
@property (retain) NSString* signatureText;
@property int32_t signatureRecordId;
@property int32_t praiseNum;
@property int32_t visitNum;
@property int32_t followedNum;
@property int32_t followNum;
@end

@implementation User_Info

- (BOOL) hasUsername {
  return !!hasUsername_;
}
- (void) setHasUsername:(BOOL) value {
  hasUsername_ = !!value;
}
@synthesize username;
- (BOOL) hasNickName {
  return !!hasNickName_;
}
- (void) setHasNickName:(BOOL) value {
  hasNickName_ = !!value;
}
@synthesize nickName;
- (BOOL) hasBirthday {
  return !!hasBirthday_;
}
- (void) setHasBirthday:(BOOL) value {
  hasBirthday_ = !!value;
}
@synthesize birthday;
- (BOOL) hasSignatureText {
  return !!hasSignatureText_;
}
- (void) setHasSignatureText:(BOOL) value {
  hasSignatureText_ = !!value;
}
@synthesize signatureText;
- (BOOL) hasSignatureRecordId {
  return !!hasSignatureRecordId_;
}
- (void) setHasSignatureRecordId:(BOOL) value {
  hasSignatureRecordId_ = !!value;
}
@synthesize signatureRecordId;
- (BOOL) hasPraiseNum {
  return !!hasPraiseNum_;
}
- (void) setHasPraiseNum:(BOOL) value {
  hasPraiseNum_ = !!value;
}
@synthesize praiseNum;
- (BOOL) hasVisitNum {
  return !!hasVisitNum_;
}
- (void) setHasVisitNum:(BOOL) value {
  hasVisitNum_ = !!value;
}
@synthesize visitNum;
- (BOOL) hasFollowedNum {
  return !!hasFollowedNum_;
}
- (void) setHasFollowedNum:(BOOL) value {
  hasFollowedNum_ = !!value;
}
@synthesize followedNum;
- (BOOL) hasFollowNum {
  return !!hasFollowNum_;
}
- (void) setHasFollowNum:(BOOL) value {
  hasFollowNum_ = !!value;
}
@synthesize followNum;
- (void) dealloc {
  self.username = nil;
  self.nickName = nil;
  self.signatureText = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.username = @"";
    self.nickName = @"";
    self.birthday = 0;
    self.signatureText = @"";
    self.signatureRecordId = 0;
    self.praiseNum = 0;
    self.visitNum = 0;
    self.followedNum = 0;
    self.followNum = 0;
  }
  return self;
}
static User_Info* defaultUser_InfoInstance = nil;
+ (void) initialize {
  if (self == [User_Info class]) {
    defaultUser_InfoInstance = [[User_Info alloc] init];
  }
}
+ (User_Info*) defaultInstance {
  return defaultUser_InfoInstance;
}
- (User_Info*) defaultInstance {
  return defaultUser_InfoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUsername) {
    [output writeString:1 value:self.username];
  }
  if (self.hasNickName) {
    [output writeString:2 value:self.nickName];
  }
  if (self.hasBirthday) {
    [output writeInt32:3 value:self.birthday];
  }
  if (self.hasSignatureText) {
    [output writeString:4 value:self.signatureText];
  }
  if (self.hasSignatureRecordId) {
    [output writeInt32:5 value:self.signatureRecordId];
  }
  if (self.hasPraiseNum) {
    [output writeInt32:6 value:self.praiseNum];
  }
  if (self.hasVisitNum) {
    [output writeInt32:7 value:self.visitNum];
  }
  if (self.hasFollowedNum) {
    [output writeInt32:8 value:self.followedNum];
  }
  if (self.hasFollowNum) {
    [output writeInt32:9 value:self.followNum];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasUsername) {
    size += computeStringSize(1, self.username);
  }
  if (self.hasNickName) {
    size += computeStringSize(2, self.nickName);
  }
  if (self.hasBirthday) {
    size += computeInt32Size(3, self.birthday);
  }
  if (self.hasSignatureText) {
    size += computeStringSize(4, self.signatureText);
  }
  if (self.hasSignatureRecordId) {
    size += computeInt32Size(5, self.signatureRecordId);
  }
  if (self.hasPraiseNum) {
    size += computeInt32Size(6, self.praiseNum);
  }
  if (self.hasVisitNum) {
    size += computeInt32Size(7, self.visitNum);
  }
  if (self.hasFollowedNum) {
    size += computeInt32Size(8, self.followedNum);
  }
  if (self.hasFollowNum) {
    size += computeInt32Size(9, self.followNum);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (User_Info*) parseFromData:(NSData*) data {
  return (User_Info*)[[[User_Info builder] mergeFromData:data] build];
}
+ (User_Info*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (User_Info*)[[[User_Info builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (User_Info*) parseFromInputStream:(NSInputStream*) input {
  return (User_Info*)[[[User_Info builder] mergeFromInputStream:input] build];
}
+ (User_Info*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (User_Info*)[[[User_Info builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (User_Info*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (User_Info*)[[[User_Info builder] mergeFromCodedInputStream:input] build];
}
+ (User_Info*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (User_Info*)[[[User_Info builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (User_Info_Builder*) builder {
  return [[[User_Info_Builder alloc] init] autorelease];
}
+ (User_Info_Builder*) builderWithPrototype:(User_Info*) prototype {
  return [[User_Info builder] mergeFrom:prototype];
}
- (User_Info_Builder*) builder {
  return [User_Info builder];
}
@end

@interface User_Info_Builder()
@property (retain) User_Info* result;
@end

@implementation User_Info_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[User_Info alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (User_Info_Builder*) clear {
  self.result = [[[User_Info alloc] init] autorelease];
  return self;
}
- (User_Info_Builder*) clone {
  return [User_Info builderWithPrototype:result];
}
- (User_Info*) defaultInstance {
  return [User_Info defaultInstance];
}
- (User_Info*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (User_Info*) buildPartial {
  User_Info* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (User_Info_Builder*) mergeFrom:(User_Info*) other {
  if (other == [User_Info defaultInstance]) {
    return self;
  }
  if (other.hasUsername) {
    [self setUsername:other.username];
  }
  if (other.hasNickName) {
    [self setNickName:other.nickName];
  }
  if (other.hasBirthday) {
    [self setBirthday:other.birthday];
  }
  if (other.hasSignatureText) {
    [self setSignatureText:other.signatureText];
  }
  if (other.hasSignatureRecordId) {
    [self setSignatureRecordId:other.signatureRecordId];
  }
  if (other.hasPraiseNum) {
    [self setPraiseNum:other.praiseNum];
  }
  if (other.hasVisitNum) {
    [self setVisitNum:other.visitNum];
  }
  if (other.hasFollowedNum) {
    [self setFollowedNum:other.followedNum];
  }
  if (other.hasFollowNum) {
    [self setFollowNum:other.followNum];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (User_Info_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (User_Info_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setUsername:[input readString]];
        break;
      }
      case 18: {
        [self setNickName:[input readString]];
        break;
      }
      case 24: {
        [self setBirthday:[input readInt32]];
        break;
      }
      case 34: {
        [self setSignatureText:[input readString]];
        break;
      }
      case 40: {
        [self setSignatureRecordId:[input readInt32]];
        break;
      }
      case 48: {
        [self setPraiseNum:[input readInt32]];
        break;
      }
      case 56: {
        [self setVisitNum:[input readInt32]];
        break;
      }
      case 64: {
        [self setFollowedNum:[input readInt32]];
        break;
      }
      case 72: {
        [self setFollowNum:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasUsername {
  return result.hasUsername;
}
- (NSString*) username {
  return result.username;
}
- (User_Info_Builder*) setUsername:(NSString*) value {
  result.hasUsername = YES;
  result.username = value;
  return self;
}
- (User_Info_Builder*) clearUsername {
  result.hasUsername = NO;
  result.username = @"";
  return self;
}
- (BOOL) hasNickName {
  return result.hasNickName;
}
- (NSString*) nickName {
  return result.nickName;
}
- (User_Info_Builder*) setNickName:(NSString*) value {
  result.hasNickName = YES;
  result.nickName = value;
  return self;
}
- (User_Info_Builder*) clearNickName {
  result.hasNickName = NO;
  result.nickName = @"";
  return self;
}
- (BOOL) hasBirthday {
  return result.hasBirthday;
}
- (int32_t) birthday {
  return result.birthday;
}
- (User_Info_Builder*) setBirthday:(int32_t) value {
  result.hasBirthday = YES;
  result.birthday = value;
  return self;
}
- (User_Info_Builder*) clearBirthday {
  result.hasBirthday = NO;
  result.birthday = 0;
  return self;
}
- (BOOL) hasSignatureText {
  return result.hasSignatureText;
}
- (NSString*) signatureText {
  return result.signatureText;
}
- (User_Info_Builder*) setSignatureText:(NSString*) value {
  result.hasSignatureText = YES;
  result.signatureText = value;
  return self;
}
- (User_Info_Builder*) clearSignatureText {
  result.hasSignatureText = NO;
  result.signatureText = @"";
  return self;
}
- (BOOL) hasSignatureRecordId {
  return result.hasSignatureRecordId;
}
- (int32_t) signatureRecordId {
  return result.signatureRecordId;
}
- (User_Info_Builder*) setSignatureRecordId:(int32_t) value {
  result.hasSignatureRecordId = YES;
  result.signatureRecordId = value;
  return self;
}
- (User_Info_Builder*) clearSignatureRecordId {
  result.hasSignatureRecordId = NO;
  result.signatureRecordId = 0;
  return self;
}
- (BOOL) hasPraiseNum {
  return result.hasPraiseNum;
}
- (int32_t) praiseNum {
  return result.praiseNum;
}
- (User_Info_Builder*) setPraiseNum:(int32_t) value {
  result.hasPraiseNum = YES;
  result.praiseNum = value;
  return self;
}
- (User_Info_Builder*) clearPraiseNum {
  result.hasPraiseNum = NO;
  result.praiseNum = 0;
  return self;
}
- (BOOL) hasVisitNum {
  return result.hasVisitNum;
}
- (int32_t) visitNum {
  return result.visitNum;
}
- (User_Info_Builder*) setVisitNum:(int32_t) value {
  result.hasVisitNum = YES;
  result.visitNum = value;
  return self;
}
- (User_Info_Builder*) clearVisitNum {
  result.hasVisitNum = NO;
  result.visitNum = 0;
  return self;
}
- (BOOL) hasFollowedNum {
  return result.hasFollowedNum;
}
- (int32_t) followedNum {
  return result.followedNum;
}
- (User_Info_Builder*) setFollowedNum:(int32_t) value {
  result.hasFollowedNum = YES;
  result.followedNum = value;
  return self;
}
- (User_Info_Builder*) clearFollowedNum {
  result.hasFollowedNum = NO;
  result.followedNum = 0;
  return self;
}
- (BOOL) hasFollowNum {
  return result.hasFollowNum;
}
- (int32_t) followNum {
  return result.followNum;
}
- (User_Info_Builder*) setFollowNum:(int32_t) value {
  result.hasFollowNum = YES;
  result.followNum = value;
  return self;
}
- (User_Info_Builder*) clearFollowNum {
  result.hasFollowNum = NO;
  result.followNum = 0;
  return self;
}
@end

