// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "UserData.pb.h"

@class DetailResponse;
@class DetailResponse_Builder;
@class LoginResponse;
@class LoginResponse_Builder;
@class User_Info;
@class User_Info_Builder;

@interface UserResponseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface LoginResponse : PBGeneratedMessage {
@private
  BOOL hasSid_:1;
  BOOL hasUserInfo_:1;
  NSString* sid;
  User_Info* userInfo;
}
- (BOOL) hasSid;
- (BOOL) hasUserInfo;
@property (readonly, retain) NSString* sid;
@property (readonly, retain) User_Info* userInfo;

+ (LoginResponse*) defaultInstance;
- (LoginResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LoginResponse_Builder*) builder;
+ (LoginResponse_Builder*) builder;
+ (LoginResponse_Builder*) builderWithPrototype:(LoginResponse*) prototype;

+ (LoginResponse*) parseFromData:(NSData*) data;
+ (LoginResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LoginResponse*) parseFromInputStream:(NSInputStream*) input;
+ (LoginResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LoginResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LoginResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LoginResponse_Builder : PBGeneratedMessage_Builder {
@private
  LoginResponse* result;
}

- (LoginResponse*) defaultInstance;

- (LoginResponse_Builder*) clear;
- (LoginResponse_Builder*) clone;

- (LoginResponse*) build;
- (LoginResponse*) buildPartial;

- (LoginResponse_Builder*) mergeFrom:(LoginResponse*) other;
- (LoginResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LoginResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSid;
- (NSString*) sid;
- (LoginResponse_Builder*) setSid:(NSString*) value;
- (LoginResponse_Builder*) clearSid;

- (BOOL) hasUserInfo;
- (User_Info*) userInfo;
- (LoginResponse_Builder*) setUserInfo:(User_Info*) value;
- (LoginResponse_Builder*) setUserInfoBuilder:(User_Info_Builder*) builderForValue;
- (LoginResponse_Builder*) mergeUserInfo:(User_Info*) value;
- (LoginResponse_Builder*) clearUserInfo;
@end

@interface DetailResponse : PBGeneratedMessage {
@private
  BOOL hasUserInfo_:1;
  User_Info* userInfo;
}
- (BOOL) hasUserInfo;
@property (readonly, retain) User_Info* userInfo;

+ (DetailResponse*) defaultInstance;
- (DetailResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DetailResponse_Builder*) builder;
+ (DetailResponse_Builder*) builder;
+ (DetailResponse_Builder*) builderWithPrototype:(DetailResponse*) prototype;

+ (DetailResponse*) parseFromData:(NSData*) data;
+ (DetailResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DetailResponse*) parseFromInputStream:(NSInputStream*) input;
+ (DetailResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DetailResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DetailResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DetailResponse_Builder : PBGeneratedMessage_Builder {
@private
  DetailResponse* result;
}

- (DetailResponse*) defaultInstance;

- (DetailResponse_Builder*) clear;
- (DetailResponse_Builder*) clone;

- (DetailResponse*) build;
- (DetailResponse*) buildPartial;

- (DetailResponse_Builder*) mergeFrom:(DetailResponse*) other;
- (DetailResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DetailResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserInfo;
- (User_Info*) userInfo;
- (DetailResponse_Builder*) setUserInfo:(User_Info*) value;
- (DetailResponse_Builder*) setUserInfoBuilder:(User_Info_Builder*) builderForValue;
- (DetailResponse_Builder*) mergeUserInfo:(User_Info*) value;
- (DetailResponse_Builder*) clearUserInfo;
@end

