// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "RoomData.pb.h"
#import "UserData.pb.h"
#import "UserResponse.pb.h"

@class Address;
@class Address_Builder;
@class DetailResponse;
@class DetailResponse_Builder;
@class List;
@class List_Builder;
@class LoginResponse;
@class LoginResponse_Builder;
@class Message_Info;
@class Message_Info_Builder;
@class RoomInfo;
@class RoomInfo_Builder;
@class UserMessageResponse;
@class UserMessageResponse_Builder;
@class User_Info;
@class User_Info_Builder;
@class UsernameExistResponse;
@class UsernameExistResponse_Builder;

@interface DataRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface List : PBGeneratedMessage {
@private
  BOOL hasIsEnd_:1;
  BOOL isEnd_:1;
  NSMutableArray* mutableRoomInfoList;
  NSMutableArray* mutableUserDetailList;
  NSMutableArray* mutableUserMessageInfoList;
}
- (BOOL) hasIsEnd;
- (BOOL) isEnd;
- (NSArray*) roomInfoList;
- (RoomInfo*) roomInfoAtIndex:(int32_t) index;
- (NSArray*) userDetailList;
- (DetailResponse*) userDetailAtIndex:(int32_t) index;
- (NSArray*) userMessageInfoList;
- (UserMessageResponse*) userMessageInfoAtIndex:(int32_t) index;

+ (List*) defaultInstance;
- (List*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (List_Builder*) builder;
+ (List_Builder*) builder;
+ (List_Builder*) builderWithPrototype:(List*) prototype;

+ (List*) parseFromData:(NSData*) data;
+ (List*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (List*) parseFromInputStream:(NSInputStream*) input;
+ (List*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (List*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (List*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface List_Builder : PBGeneratedMessage_Builder {
@private
  List* result;
}

- (List*) defaultInstance;

- (List_Builder*) clear;
- (List_Builder*) clone;

- (List*) build;
- (List*) buildPartial;

- (List_Builder*) mergeFrom:(List*) other;
- (List_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (List_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsEnd;
- (BOOL) isEnd;
- (List_Builder*) setIsEnd:(BOOL) value;
- (List_Builder*) clearIsEnd;

- (NSArray*) roomInfoList;
- (RoomInfo*) roomInfoAtIndex:(int32_t) index;
- (List_Builder*) replaceRoomInfoAtIndex:(int32_t) index with:(RoomInfo*) value;
- (List_Builder*) addRoomInfo:(RoomInfo*) value;
- (List_Builder*) addAllRoomInfo:(NSArray*) values;
- (List_Builder*) clearRoomInfoList;

- (NSArray*) userDetailList;
- (DetailResponse*) userDetailAtIndex:(int32_t) index;
- (List_Builder*) replaceUserDetailAtIndex:(int32_t) index with:(DetailResponse*) value;
- (List_Builder*) addUserDetail:(DetailResponse*) value;
- (List_Builder*) addAllUserDetail:(NSArray*) values;
- (List_Builder*) clearUserDetailList;

- (NSArray*) userMessageInfoList;
- (UserMessageResponse*) userMessageInfoAtIndex:(int32_t) index;
- (List_Builder*) replaceUserMessageInfoAtIndex:(int32_t) index with:(UserMessageResponse*) value;
- (List_Builder*) addUserMessageInfo:(UserMessageResponse*) value;
- (List_Builder*) addAllUserMessageInfo:(NSArray*) values;
- (List_Builder*) clearUserMessageInfoList;
@end

