// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "RoomData.pb.h"
#import "UserData.pb.h"

@class Address;
@class Address_Builder;
@class List;
@class List_Builder;
@class RoomInfo;
@class RoomInfo_Builder;
@class User_Info;
@class User_Info_Builder;

@interface DataRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface List : PBGeneratedMessage {
@private
  BOOL hasIsEnd_:1;
  BOOL isEnd_:1;
  NSMutableArray* mutableRoomInfoListList;
  NSMutableArray* mutableUserInfoList;
}
- (BOOL) hasIsEnd;
- (BOOL) isEnd;
- (NSArray*) roomInfoListList;
- (RoomInfo*) roomInfoListAtIndex:(int32_t) index;
- (NSArray*) userInfoList;
- (User_Info*) userInfoAtIndex:(int32_t) index;

+ (List*) defaultInstance;
- (List*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (List_Builder*) builder;
+ (List_Builder*) builder;
+ (List_Builder*) builderWithPrototype:(List*) prototype;

+ (List*) parseFromData:(NSData*) data;
+ (List*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (List*) parseFromInputStream:(NSInputStream*) input;
+ (List*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (List*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (List*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface List_Builder : PBGeneratedMessage_Builder {
@private
  List* result;
}

- (List*) defaultInstance;

- (List_Builder*) clear;
- (List_Builder*) clone;

- (List*) build;
- (List*) buildPartial;

- (List_Builder*) mergeFrom:(List*) other;
- (List_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (List_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsEnd;
- (BOOL) isEnd;
- (List_Builder*) setIsEnd:(BOOL) value;
- (List_Builder*) clearIsEnd;

- (NSArray*) roomInfoListList;
- (RoomInfo*) roomInfoListAtIndex:(int32_t) index;
- (List_Builder*) replaceRoomInfoListAtIndex:(int32_t) index with:(RoomInfo*) value;
- (List_Builder*) addRoomInfoList:(RoomInfo*) value;
- (List_Builder*) addAllRoomInfoList:(NSArray*) values;
- (List_Builder*) clearRoomInfoListList;

- (NSArray*) userInfoList;
- (User_Info*) userInfoAtIndex:(int32_t) index;
- (List_Builder*) replaceUserInfoAtIndex:(int32_t) index with:(User_Info*) value;
- (List_Builder*) addUserInfo:(User_Info*) value;
- (List_Builder*) addAllUserInfo:(NSArray*) values;
- (List_Builder*) clearUserInfoList;
@end

