// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "UserResponse.pb.h"
#import "RoomResponse.pb.h"
#import "Data.pb.h"

@class Address;
@class Address_Builder;
@class CreateRoomResponse;
@class CreateRoomResponse_Builder;
@class DetailResponse;
@class DetailResponse_Builder;
@class HTTPResponse;
@class HTTPResponse_Builder;
@class List;
@class List_Builder;
@class LoginResponse;
@class LoginResponse_Builder;
@class Message_Info;
@class Message_Info_Builder;
@class RoomInfo;
@class RoomInfoResponse;
@class RoomInfoResponse_Builder;
@class RoomInfo_Builder;
@class UserMessageResponse;
@class UserMessageResponse_Builder;
@class User_Info;
@class User_Info_Builder;
@class UsernameExistResponse;
@class UsernameExistResponse_Builder;

@interface ResponseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface HTTPResponse : PBGeneratedMessage {
@private
  BOOL hasSuccess_:1;
  BOOL hasCode_:1;
  BOOL hasMsg_:1;
  BOOL hasServerTime_:1;
  BOOL hasLoginResponse_:1;
  BOOL hasDetailResponse_:1;
  BOOL hasExistResponse_:1;
  BOOL hasRoomInfoResponse_:1;
  BOOL hasCreateRoomResponse_:1;
  BOOL hasList_:1;
  BOOL success_:1;
  int32_t code;
  NSString* msg;
  NSString* serverTime;
  LoginResponse* loginResponse;
  DetailResponse* detailResponse;
  UsernameExistResponse* existResponse;
  RoomInfoResponse* roomInfoResponse;
  CreateRoomResponse* createRoomResponse;
  List* list;
}
- (BOOL) hasCode;
- (BOOL) hasSuccess;
- (BOOL) hasMsg;
- (BOOL) hasServerTime;
- (BOOL) hasLoginResponse;
- (BOOL) hasDetailResponse;
- (BOOL) hasExistResponse;
- (BOOL) hasRoomInfoResponse;
- (BOOL) hasCreateRoomResponse;
- (BOOL) hasList;
@property (readonly) int32_t code;
- (BOOL) success;
@property (readonly, retain) NSString* msg;
@property (readonly, retain) NSString* serverTime;
@property (readonly, retain) LoginResponse* loginResponse;
@property (readonly, retain) DetailResponse* detailResponse;
@property (readonly, retain) UsernameExistResponse* existResponse;
@property (readonly, retain) RoomInfoResponse* roomInfoResponse;
@property (readonly, retain) CreateRoomResponse* createRoomResponse;
@property (readonly, retain) List* list;

+ (HTTPResponse*) defaultInstance;
- (HTTPResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HTTPResponse_Builder*) builder;
+ (HTTPResponse_Builder*) builder;
+ (HTTPResponse_Builder*) builderWithPrototype:(HTTPResponse*) prototype;

+ (HTTPResponse*) parseFromData:(NSData*) data;
+ (HTTPResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HTTPResponse*) parseFromInputStream:(NSInputStream*) input;
+ (HTTPResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HTTPResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HTTPResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HTTPResponse_Builder : PBGeneratedMessage_Builder {
@private
  HTTPResponse* result;
}

- (HTTPResponse*) defaultInstance;

- (HTTPResponse_Builder*) clear;
- (HTTPResponse_Builder*) clone;

- (HTTPResponse*) build;
- (HTTPResponse*) buildPartial;

- (HTTPResponse_Builder*) mergeFrom:(HTTPResponse*) other;
- (HTTPResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HTTPResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCode;
- (int32_t) code;
- (HTTPResponse_Builder*) setCode:(int32_t) value;
- (HTTPResponse_Builder*) clearCode;

- (BOOL) hasSuccess;
- (BOOL) success;
- (HTTPResponse_Builder*) setSuccess:(BOOL) value;
- (HTTPResponse_Builder*) clearSuccess;

- (BOOL) hasMsg;
- (NSString*) msg;
- (HTTPResponse_Builder*) setMsg:(NSString*) value;
- (HTTPResponse_Builder*) clearMsg;

- (BOOL) hasServerTime;
- (NSString*) serverTime;
- (HTTPResponse_Builder*) setServerTime:(NSString*) value;
- (HTTPResponse_Builder*) clearServerTime;

- (BOOL) hasLoginResponse;
- (LoginResponse*) loginResponse;
- (HTTPResponse_Builder*) setLoginResponse:(LoginResponse*) value;
- (HTTPResponse_Builder*) setLoginResponseBuilder:(LoginResponse_Builder*) builderForValue;
- (HTTPResponse_Builder*) mergeLoginResponse:(LoginResponse*) value;
- (HTTPResponse_Builder*) clearLoginResponse;

- (BOOL) hasDetailResponse;
- (DetailResponse*) detailResponse;
- (HTTPResponse_Builder*) setDetailResponse:(DetailResponse*) value;
- (HTTPResponse_Builder*) setDetailResponseBuilder:(DetailResponse_Builder*) builderForValue;
- (HTTPResponse_Builder*) mergeDetailResponse:(DetailResponse*) value;
- (HTTPResponse_Builder*) clearDetailResponse;

- (BOOL) hasExistResponse;
- (UsernameExistResponse*) existResponse;
- (HTTPResponse_Builder*) setExistResponse:(UsernameExistResponse*) value;
- (HTTPResponse_Builder*) setExistResponseBuilder:(UsernameExistResponse_Builder*) builderForValue;
- (HTTPResponse_Builder*) mergeExistResponse:(UsernameExistResponse*) value;
- (HTTPResponse_Builder*) clearExistResponse;

- (BOOL) hasRoomInfoResponse;
- (RoomInfoResponse*) roomInfoResponse;
- (HTTPResponse_Builder*) setRoomInfoResponse:(RoomInfoResponse*) value;
- (HTTPResponse_Builder*) setRoomInfoResponseBuilder:(RoomInfoResponse_Builder*) builderForValue;
- (HTTPResponse_Builder*) mergeRoomInfoResponse:(RoomInfoResponse*) value;
- (HTTPResponse_Builder*) clearRoomInfoResponse;

- (BOOL) hasCreateRoomResponse;
- (CreateRoomResponse*) createRoomResponse;
- (HTTPResponse_Builder*) setCreateRoomResponse:(CreateRoomResponse*) value;
- (HTTPResponse_Builder*) setCreateRoomResponseBuilder:(CreateRoomResponse_Builder*) builderForValue;
- (HTTPResponse_Builder*) mergeCreateRoomResponse:(CreateRoomResponse*) value;
- (HTTPResponse_Builder*) clearCreateRoomResponse;

- (BOOL) hasList;
- (List*) list;
- (HTTPResponse_Builder*) setList:(List*) value;
- (HTTPResponse_Builder*) setListBuilder:(List_Builder*) builderForValue;
- (HTTPResponse_Builder*) mergeList:(List*) value;
- (HTTPResponse_Builder*) clearList;
@end

