// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "UserResponse.pb.h"

@class HTTPResponse;
@class HTTPResponse_Builder;
@class LoginResponse;
@class LoginResponse_Builder;
@class User_Info;
@class User_Info_Builder;

@interface ResponseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface HTTPResponse : PBGeneratedMessage {
@private
  BOOL hasSuccess_:1;
  BOOL hasCode_:1;
  BOOL hasMsg_:1;
  BOOL hasLoginResponse_:1;
  BOOL success_:1;
  int32_t code;
  NSString* msg;
  LoginResponse* loginResponse;
}
- (BOOL) hasCode;
- (BOOL) hasSuccess;
- (BOOL) hasMsg;
- (BOOL) hasLoginResponse;
@property (readonly) int32_t code;
- (BOOL) success;
@property (readonly, retain) NSString* msg;
@property (readonly, retain) LoginResponse* loginResponse;

+ (HTTPResponse*) defaultInstance;
- (HTTPResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HTTPResponse_Builder*) builder;
+ (HTTPResponse_Builder*) builder;
+ (HTTPResponse_Builder*) builderWithPrototype:(HTTPResponse*) prototype;

+ (HTTPResponse*) parseFromData:(NSData*) data;
+ (HTTPResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HTTPResponse*) parseFromInputStream:(NSInputStream*) input;
+ (HTTPResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HTTPResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HTTPResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HTTPResponse_Builder : PBGeneratedMessage_Builder {
@private
  HTTPResponse* result;
}

- (HTTPResponse*) defaultInstance;

- (HTTPResponse_Builder*) clear;
- (HTTPResponse_Builder*) clone;

- (HTTPResponse*) build;
- (HTTPResponse*) buildPartial;

- (HTTPResponse_Builder*) mergeFrom:(HTTPResponse*) other;
- (HTTPResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HTTPResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCode;
- (int32_t) code;
- (HTTPResponse_Builder*) setCode:(int32_t) value;
- (HTTPResponse_Builder*) clearCode;

- (BOOL) hasSuccess;
- (BOOL) success;
- (HTTPResponse_Builder*) setSuccess:(BOOL) value;
- (HTTPResponse_Builder*) clearSuccess;

- (BOOL) hasMsg;
- (NSString*) msg;
- (HTTPResponse_Builder*) setMsg:(NSString*) value;
- (HTTPResponse_Builder*) clearMsg;

- (BOOL) hasLoginResponse;
- (LoginResponse*) loginResponse;
- (HTTPResponse_Builder*) setLoginResponse:(LoginResponse*) value;
- (HTTPResponse_Builder*) setLoginResponseBuilder:(LoginResponse_Builder*) builderForValue;
- (HTTPResponse_Builder*) mergeLoginResponse:(LoginResponse*) value;
- (HTTPResponse_Builder*) clearLoginResponse;
@end

