// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Response.pb.h"

@implementation ResponseRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [ResponseRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [UserResponseRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface HTTPResponse ()
@property int32_t code;
@property BOOL success;
@property (retain) NSString* msg;
@property (retain) LoginResponse* loginResponse;
@end

@implementation HTTPResponse

- (BOOL) hasCode {
  return !!hasCode_;
}
- (void) setHasCode:(BOOL) value {
  hasCode_ = !!value;
}
@synthesize code;
- (BOOL) hasSuccess {
  return !!hasSuccess_;
}
- (void) setHasSuccess:(BOOL) value {
  hasSuccess_ = !!value;
}
- (BOOL) success {
  return !!success_;
}
- (void) setSuccess:(BOOL) value {
  success_ = !!value;
}
- (BOOL) hasMsg {
  return !!hasMsg_;
}
- (void) setHasMsg:(BOOL) value {
  hasMsg_ = !!value;
}
@synthesize msg;
- (BOOL) hasLoginResponse {
  return !!hasLoginResponse_;
}
- (void) setHasLoginResponse:(BOOL) value {
  hasLoginResponse_ = !!value;
}
@synthesize loginResponse;
- (void) dealloc {
  self.msg = nil;
  self.loginResponse = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.code = 0;
    self.success = NO;
    self.msg = @"";
    self.loginResponse = [LoginResponse defaultInstance];
  }
  return self;
}
static HTTPResponse* defaultHTTPResponseInstance = nil;
+ (void) initialize {
  if (self == [HTTPResponse class]) {
    defaultHTTPResponseInstance = [[HTTPResponse alloc] init];
  }
}
+ (HTTPResponse*) defaultInstance {
  return defaultHTTPResponseInstance;
}
- (HTTPResponse*) defaultInstance {
  return defaultHTTPResponseInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasCode) {
    [output writeInt32:1 value:self.code];
  }
  if (self.hasSuccess) {
    [output writeBool:2 value:self.success];
  }
  if (self.hasMsg) {
    [output writeString:3 value:self.msg];
  }
  if (self.hasLoginResponse) {
    [output writeMessage:4 value:self.loginResponse];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasCode) {
    size += computeInt32Size(1, self.code);
  }
  if (self.hasSuccess) {
    size += computeBoolSize(2, self.success);
  }
  if (self.hasMsg) {
    size += computeStringSize(3, self.msg);
  }
  if (self.hasLoginResponse) {
    size += computeMessageSize(4, self.loginResponse);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (HTTPResponse*) parseFromData:(NSData*) data {
  return (HTTPResponse*)[[[HTTPResponse builder] mergeFromData:data] build];
}
+ (HTTPResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (HTTPResponse*)[[[HTTPResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (HTTPResponse*) parseFromInputStream:(NSInputStream*) input {
  return (HTTPResponse*)[[[HTTPResponse builder] mergeFromInputStream:input] build];
}
+ (HTTPResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (HTTPResponse*)[[[HTTPResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (HTTPResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (HTTPResponse*)[[[HTTPResponse builder] mergeFromCodedInputStream:input] build];
}
+ (HTTPResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (HTTPResponse*)[[[HTTPResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (HTTPResponse_Builder*) builder {
  return [[[HTTPResponse_Builder alloc] init] autorelease];
}
+ (HTTPResponse_Builder*) builderWithPrototype:(HTTPResponse*) prototype {
  return [[HTTPResponse builder] mergeFrom:prototype];
}
- (HTTPResponse_Builder*) builder {
  return [HTTPResponse builder];
}
@end

@interface HTTPResponse_Builder()
@property (retain) HTTPResponse* result;
@end

@implementation HTTPResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[HTTPResponse alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (HTTPResponse_Builder*) clear {
  self.result = [[[HTTPResponse alloc] init] autorelease];
  return self;
}
- (HTTPResponse_Builder*) clone {
  return [HTTPResponse builderWithPrototype:result];
}
- (HTTPResponse*) defaultInstance {
  return [HTTPResponse defaultInstance];
}
- (HTTPResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (HTTPResponse*) buildPartial {
  HTTPResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (HTTPResponse_Builder*) mergeFrom:(HTTPResponse*) other {
  if (other == [HTTPResponse defaultInstance]) {
    return self;
  }
  if (other.hasCode) {
    [self setCode:other.code];
  }
  if (other.hasSuccess) {
    [self setSuccess:other.success];
  }
  if (other.hasMsg) {
    [self setMsg:other.msg];
  }
  if (other.hasLoginResponse) {
    [self mergeLoginResponse:other.loginResponse];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (HTTPResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (HTTPResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setCode:[input readInt32]];
        break;
      }
      case 16: {
        [self setSuccess:[input readBool]];
        break;
      }
      case 26: {
        [self setMsg:[input readString]];
        break;
      }
      case 34: {
        LoginResponse_Builder* subBuilder = [LoginResponse builder];
        if (self.hasLoginResponse) {
          [subBuilder mergeFrom:self.loginResponse];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setLoginResponse:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasCode {
  return result.hasCode;
}
- (int32_t) code {
  return result.code;
}
- (HTTPResponse_Builder*) setCode:(int32_t) value {
  result.hasCode = YES;
  result.code = value;
  return self;
}
- (HTTPResponse_Builder*) clearCode {
  result.hasCode = NO;
  result.code = 0;
  return self;
}
- (BOOL) hasSuccess {
  return result.hasSuccess;
}
- (BOOL) success {
  return result.success;
}
- (HTTPResponse_Builder*) setSuccess:(BOOL) value {
  result.hasSuccess = YES;
  result.success = value;
  return self;
}
- (HTTPResponse_Builder*) clearSuccess {
  result.hasSuccess = NO;
  result.success = NO;
  return self;
}
- (BOOL) hasMsg {
  return result.hasMsg;
}
- (NSString*) msg {
  return result.msg;
}
- (HTTPResponse_Builder*) setMsg:(NSString*) value {
  result.hasMsg = YES;
  result.msg = value;
  return self;
}
- (HTTPResponse_Builder*) clearMsg {
  result.hasMsg = NO;
  result.msg = @"";
  return self;
}
- (BOOL) hasLoginResponse {
  return result.hasLoginResponse;
}
- (LoginResponse*) loginResponse {
  return result.loginResponse;
}
- (HTTPResponse_Builder*) setLoginResponse:(LoginResponse*) value {
  result.hasLoginResponse = YES;
  result.loginResponse = value;
  return self;
}
- (HTTPResponse_Builder*) setLoginResponseBuilder:(LoginResponse_Builder*) builderForValue {
  return [self setLoginResponse:[builderForValue build]];
}
- (HTTPResponse_Builder*) mergeLoginResponse:(LoginResponse*) value {
  if (result.hasLoginResponse &&
      result.loginResponse != [LoginResponse defaultInstance]) {
    result.loginResponse =
      [[[LoginResponse builderWithPrototype:result.loginResponse] mergeFrom:value] buildPartial];
  } else {
    result.loginResponse = value;
  }
  result.hasLoginResponse = YES;
  return self;
}
- (HTTPResponse_Builder*) clearLoginResponse {
  result.hasLoginResponse = NO;
  result.loginResponse = [LoginResponse defaultInstance];
  return self;
}
@end

