// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Response.pb.h"

@implementation ResponseRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [ResponseRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [UserResponseRoot registerAllExtensions:registry];
    [RoomResponseRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface HTTPResponse ()
@property int32_t code;
@property BOOL success;
@property (retain) NSString* msg;
@property (retain) LoginResponse* loginResponse;
@property (retain) DetailResponse* detailResponse;
@property (retain) UsernameExistResponse* existResponse;
@property (retain) ShowRoomListResponse* roomListResponse;
@property (retain) RoomPeopleListResponse* roomPeopleListResponse;
@property (retain) RoomInfoResponse* roomInfoResponse;
@end

@implementation HTTPResponse

- (BOOL) hasCode {
  return !!hasCode_;
}
- (void) setHasCode:(BOOL) value {
  hasCode_ = !!value;
}
@synthesize code;
- (BOOL) hasSuccess {
  return !!hasSuccess_;
}
- (void) setHasSuccess:(BOOL) value {
  hasSuccess_ = !!value;
}
- (BOOL) success {
  return !!success_;
}
- (void) setSuccess:(BOOL) value {
  success_ = !!value;
}
- (BOOL) hasMsg {
  return !!hasMsg_;
}
- (void) setHasMsg:(BOOL) value {
  hasMsg_ = !!value;
}
@synthesize msg;
- (BOOL) hasLoginResponse {
  return !!hasLoginResponse_;
}
- (void) setHasLoginResponse:(BOOL) value {
  hasLoginResponse_ = !!value;
}
@synthesize loginResponse;
- (BOOL) hasDetailResponse {
  return !!hasDetailResponse_;
}
- (void) setHasDetailResponse:(BOOL) value {
  hasDetailResponse_ = !!value;
}
@synthesize detailResponse;
- (BOOL) hasExistResponse {
  return !!hasExistResponse_;
}
- (void) setHasExistResponse:(BOOL) value {
  hasExistResponse_ = !!value;
}
@synthesize existResponse;
- (BOOL) hasRoomListResponse {
  return !!hasRoomListResponse_;
}
- (void) setHasRoomListResponse:(BOOL) value {
  hasRoomListResponse_ = !!value;
}
@synthesize roomListResponse;
- (BOOL) hasRoomPeopleListResponse {
  return !!hasRoomPeopleListResponse_;
}
- (void) setHasRoomPeopleListResponse:(BOOL) value {
  hasRoomPeopleListResponse_ = !!value;
}
@synthesize roomPeopleListResponse;
- (BOOL) hasRoomInfoResponse {
  return !!hasRoomInfoResponse_;
}
- (void) setHasRoomInfoResponse:(BOOL) value {
  hasRoomInfoResponse_ = !!value;
}
@synthesize roomInfoResponse;
- (void) dealloc {
  self.msg = nil;
  self.loginResponse = nil;
  self.detailResponse = nil;
  self.existResponse = nil;
  self.roomListResponse = nil;
  self.roomPeopleListResponse = nil;
  self.roomInfoResponse = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.code = 0;
    self.success = NO;
    self.msg = @"";
    self.loginResponse = [LoginResponse defaultInstance];
    self.detailResponse = [DetailResponse defaultInstance];
    self.existResponse = [UsernameExistResponse defaultInstance];
    self.roomListResponse = [ShowRoomListResponse defaultInstance];
    self.roomPeopleListResponse = [RoomPeopleListResponse defaultInstance];
    self.roomInfoResponse = [RoomInfoResponse defaultInstance];
  }
  return self;
}
static HTTPResponse* defaultHTTPResponseInstance = nil;
+ (void) initialize {
  if (self == [HTTPResponse class]) {
    defaultHTTPResponseInstance = [[HTTPResponse alloc] init];
  }
}
+ (HTTPResponse*) defaultInstance {
  return defaultHTTPResponseInstance;
}
- (HTTPResponse*) defaultInstance {
  return defaultHTTPResponseInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasCode) {
    [output writeInt32:1 value:self.code];
  }
  if (self.hasSuccess) {
    [output writeBool:2 value:self.success];
  }
  if (self.hasMsg) {
    [output writeString:3 value:self.msg];
  }
  if (self.hasLoginResponse) {
    [output writeMessage:4 value:self.loginResponse];
  }
  if (self.hasDetailResponse) {
    [output writeMessage:5 value:self.detailResponse];
  }
  if (self.hasExistResponse) {
    [output writeMessage:6 value:self.existResponse];
  }
  if (self.hasRoomListResponse) {
    [output writeMessage:7 value:self.roomListResponse];
  }
  if (self.hasRoomPeopleListResponse) {
    [output writeMessage:8 value:self.roomPeopleListResponse];
  }
  if (self.hasRoomInfoResponse) {
    [output writeMessage:9 value:self.roomInfoResponse];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasCode) {
    size += computeInt32Size(1, self.code);
  }
  if (self.hasSuccess) {
    size += computeBoolSize(2, self.success);
  }
  if (self.hasMsg) {
    size += computeStringSize(3, self.msg);
  }
  if (self.hasLoginResponse) {
    size += computeMessageSize(4, self.loginResponse);
  }
  if (self.hasDetailResponse) {
    size += computeMessageSize(5, self.detailResponse);
  }
  if (self.hasExistResponse) {
    size += computeMessageSize(6, self.existResponse);
  }
  if (self.hasRoomListResponse) {
    size += computeMessageSize(7, self.roomListResponse);
  }
  if (self.hasRoomPeopleListResponse) {
    size += computeMessageSize(8, self.roomPeopleListResponse);
  }
  if (self.hasRoomInfoResponse) {
    size += computeMessageSize(9, self.roomInfoResponse);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (HTTPResponse*) parseFromData:(NSData*) data {
  return (HTTPResponse*)[[[HTTPResponse builder] mergeFromData:data] build];
}
+ (HTTPResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (HTTPResponse*)[[[HTTPResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (HTTPResponse*) parseFromInputStream:(NSInputStream*) input {
  return (HTTPResponse*)[[[HTTPResponse builder] mergeFromInputStream:input] build];
}
+ (HTTPResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (HTTPResponse*)[[[HTTPResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (HTTPResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (HTTPResponse*)[[[HTTPResponse builder] mergeFromCodedInputStream:input] build];
}
+ (HTTPResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (HTTPResponse*)[[[HTTPResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (HTTPResponse_Builder*) builder {
  return [[[HTTPResponse_Builder alloc] init] autorelease];
}
+ (HTTPResponse_Builder*) builderWithPrototype:(HTTPResponse*) prototype {
  return [[HTTPResponse builder] mergeFrom:prototype];
}
- (HTTPResponse_Builder*) builder {
  return [HTTPResponse builder];
}
@end

@interface HTTPResponse_Builder()
@property (retain) HTTPResponse* result;
@end

@implementation HTTPResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[HTTPResponse alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (HTTPResponse_Builder*) clear {
  self.result = [[[HTTPResponse alloc] init] autorelease];
  return self;
}
- (HTTPResponse_Builder*) clone {
  return [HTTPResponse builderWithPrototype:result];
}
- (HTTPResponse*) defaultInstance {
  return [HTTPResponse defaultInstance];
}
- (HTTPResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (HTTPResponse*) buildPartial {
  HTTPResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (HTTPResponse_Builder*) mergeFrom:(HTTPResponse*) other {
  if (other == [HTTPResponse defaultInstance]) {
    return self;
  }
  if (other.hasCode) {
    [self setCode:other.code];
  }
  if (other.hasSuccess) {
    [self setSuccess:other.success];
  }
  if (other.hasMsg) {
    [self setMsg:other.msg];
  }
  if (other.hasLoginResponse) {
    [self mergeLoginResponse:other.loginResponse];
  }
  if (other.hasDetailResponse) {
    [self mergeDetailResponse:other.detailResponse];
  }
  if (other.hasExistResponse) {
    [self mergeExistResponse:other.existResponse];
  }
  if (other.hasRoomListResponse) {
    [self mergeRoomListResponse:other.roomListResponse];
  }
  if (other.hasRoomPeopleListResponse) {
    [self mergeRoomPeopleListResponse:other.roomPeopleListResponse];
  }
  if (other.hasRoomInfoResponse) {
    [self mergeRoomInfoResponse:other.roomInfoResponse];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (HTTPResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (HTTPResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setCode:[input readInt32]];
        break;
      }
      case 16: {
        [self setSuccess:[input readBool]];
        break;
      }
      case 26: {
        [self setMsg:[input readString]];
        break;
      }
      case 34: {
        LoginResponse_Builder* subBuilder = [LoginResponse builder];
        if (self.hasLoginResponse) {
          [subBuilder mergeFrom:self.loginResponse];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setLoginResponse:[subBuilder buildPartial]];
        break;
      }
      case 42: {
        DetailResponse_Builder* subBuilder = [DetailResponse builder];
        if (self.hasDetailResponse) {
          [subBuilder mergeFrom:self.detailResponse];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setDetailResponse:[subBuilder buildPartial]];
        break;
      }
      case 50: {
        UsernameExistResponse_Builder* subBuilder = [UsernameExistResponse builder];
        if (self.hasExistResponse) {
          [subBuilder mergeFrom:self.existResponse];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setExistResponse:[subBuilder buildPartial]];
        break;
      }
      case 58: {
        ShowRoomListResponse_Builder* subBuilder = [ShowRoomListResponse builder];
        if (self.hasRoomListResponse) {
          [subBuilder mergeFrom:self.roomListResponse];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setRoomListResponse:[subBuilder buildPartial]];
        break;
      }
      case 66: {
        RoomPeopleListResponse_Builder* subBuilder = [RoomPeopleListResponse builder];
        if (self.hasRoomPeopleListResponse) {
          [subBuilder mergeFrom:self.roomPeopleListResponse];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setRoomPeopleListResponse:[subBuilder buildPartial]];
        break;
      }
      case 74: {
        RoomInfoResponse_Builder* subBuilder = [RoomInfoResponse builder];
        if (self.hasRoomInfoResponse) {
          [subBuilder mergeFrom:self.roomInfoResponse];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setRoomInfoResponse:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasCode {
  return result.hasCode;
}
- (int32_t) code {
  return result.code;
}
- (HTTPResponse_Builder*) setCode:(int32_t) value {
  result.hasCode = YES;
  result.code = value;
  return self;
}
- (HTTPResponse_Builder*) clearCode {
  result.hasCode = NO;
  result.code = 0;
  return self;
}
- (BOOL) hasSuccess {
  return result.hasSuccess;
}
- (BOOL) success {
  return result.success;
}
- (HTTPResponse_Builder*) setSuccess:(BOOL) value {
  result.hasSuccess = YES;
  result.success = value;
  return self;
}
- (HTTPResponse_Builder*) clearSuccess {
  result.hasSuccess = NO;
  result.success = NO;
  return self;
}
- (BOOL) hasMsg {
  return result.hasMsg;
}
- (NSString*) msg {
  return result.msg;
}
- (HTTPResponse_Builder*) setMsg:(NSString*) value {
  result.hasMsg = YES;
  result.msg = value;
  return self;
}
- (HTTPResponse_Builder*) clearMsg {
  result.hasMsg = NO;
  result.msg = @"";
  return self;
}
- (BOOL) hasLoginResponse {
  return result.hasLoginResponse;
}
- (LoginResponse*) loginResponse {
  return result.loginResponse;
}
- (HTTPResponse_Builder*) setLoginResponse:(LoginResponse*) value {
  result.hasLoginResponse = YES;
  result.loginResponse = value;
  return self;
}
- (HTTPResponse_Builder*) setLoginResponseBuilder:(LoginResponse_Builder*) builderForValue {
  return [self setLoginResponse:[builderForValue build]];
}
- (HTTPResponse_Builder*) mergeLoginResponse:(LoginResponse*) value {
  if (result.hasLoginResponse &&
      result.loginResponse != [LoginResponse defaultInstance]) {
    result.loginResponse =
      [[[LoginResponse builderWithPrototype:result.loginResponse] mergeFrom:value] buildPartial];
  } else {
    result.loginResponse = value;
  }
  result.hasLoginResponse = YES;
  return self;
}
- (HTTPResponse_Builder*) clearLoginResponse {
  result.hasLoginResponse = NO;
  result.loginResponse = [LoginResponse defaultInstance];
  return self;
}
- (BOOL) hasDetailResponse {
  return result.hasDetailResponse;
}
- (DetailResponse*) detailResponse {
  return result.detailResponse;
}
- (HTTPResponse_Builder*) setDetailResponse:(DetailResponse*) value {
  result.hasDetailResponse = YES;
  result.detailResponse = value;
  return self;
}
- (HTTPResponse_Builder*) setDetailResponseBuilder:(DetailResponse_Builder*) builderForValue {
  return [self setDetailResponse:[builderForValue build]];
}
- (HTTPResponse_Builder*) mergeDetailResponse:(DetailResponse*) value {
  if (result.hasDetailResponse &&
      result.detailResponse != [DetailResponse defaultInstance]) {
    result.detailResponse =
      [[[DetailResponse builderWithPrototype:result.detailResponse] mergeFrom:value] buildPartial];
  } else {
    result.detailResponse = value;
  }
  result.hasDetailResponse = YES;
  return self;
}
- (HTTPResponse_Builder*) clearDetailResponse {
  result.hasDetailResponse = NO;
  result.detailResponse = [DetailResponse defaultInstance];
  return self;
}
- (BOOL) hasExistResponse {
  return result.hasExistResponse;
}
- (UsernameExistResponse*) existResponse {
  return result.existResponse;
}
- (HTTPResponse_Builder*) setExistResponse:(UsernameExistResponse*) value {
  result.hasExistResponse = YES;
  result.existResponse = value;
  return self;
}
- (HTTPResponse_Builder*) setExistResponseBuilder:(UsernameExistResponse_Builder*) builderForValue {
  return [self setExistResponse:[builderForValue build]];
}
- (HTTPResponse_Builder*) mergeExistResponse:(UsernameExistResponse*) value {
  if (result.hasExistResponse &&
      result.existResponse != [UsernameExistResponse defaultInstance]) {
    result.existResponse =
      [[[UsernameExistResponse builderWithPrototype:result.existResponse] mergeFrom:value] buildPartial];
  } else {
    result.existResponse = value;
  }
  result.hasExistResponse = YES;
  return self;
}
- (HTTPResponse_Builder*) clearExistResponse {
  result.hasExistResponse = NO;
  result.existResponse = [UsernameExistResponse defaultInstance];
  return self;
}
- (BOOL) hasRoomListResponse {
  return result.hasRoomListResponse;
}
- (ShowRoomListResponse*) roomListResponse {
  return result.roomListResponse;
}
- (HTTPResponse_Builder*) setRoomListResponse:(ShowRoomListResponse*) value {
  result.hasRoomListResponse = YES;
  result.roomListResponse = value;
  return self;
}
- (HTTPResponse_Builder*) setRoomListResponseBuilder:(ShowRoomListResponse_Builder*) builderForValue {
  return [self setRoomListResponse:[builderForValue build]];
}
- (HTTPResponse_Builder*) mergeRoomListResponse:(ShowRoomListResponse*) value {
  if (result.hasRoomListResponse &&
      result.roomListResponse != [ShowRoomListResponse defaultInstance]) {
    result.roomListResponse =
      [[[ShowRoomListResponse builderWithPrototype:result.roomListResponse] mergeFrom:value] buildPartial];
  } else {
    result.roomListResponse = value;
  }
  result.hasRoomListResponse = YES;
  return self;
}
- (HTTPResponse_Builder*) clearRoomListResponse {
  result.hasRoomListResponse = NO;
  result.roomListResponse = [ShowRoomListResponse defaultInstance];
  return self;
}
- (BOOL) hasRoomPeopleListResponse {
  return result.hasRoomPeopleListResponse;
}
- (RoomPeopleListResponse*) roomPeopleListResponse {
  return result.roomPeopleListResponse;
}
- (HTTPResponse_Builder*) setRoomPeopleListResponse:(RoomPeopleListResponse*) value {
  result.hasRoomPeopleListResponse = YES;
  result.roomPeopleListResponse = value;
  return self;
}
- (HTTPResponse_Builder*) setRoomPeopleListResponseBuilder:(RoomPeopleListResponse_Builder*) builderForValue {
  return [self setRoomPeopleListResponse:[builderForValue build]];
}
- (HTTPResponse_Builder*) mergeRoomPeopleListResponse:(RoomPeopleListResponse*) value {
  if (result.hasRoomPeopleListResponse &&
      result.roomPeopleListResponse != [RoomPeopleListResponse defaultInstance]) {
    result.roomPeopleListResponse =
      [[[RoomPeopleListResponse builderWithPrototype:result.roomPeopleListResponse] mergeFrom:value] buildPartial];
  } else {
    result.roomPeopleListResponse = value;
  }
  result.hasRoomPeopleListResponse = YES;
  return self;
}
- (HTTPResponse_Builder*) clearRoomPeopleListResponse {
  result.hasRoomPeopleListResponse = NO;
  result.roomPeopleListResponse = [RoomPeopleListResponse defaultInstance];
  return self;
}
- (BOOL) hasRoomInfoResponse {
  return result.hasRoomInfoResponse;
}
- (RoomInfoResponse*) roomInfoResponse {
  return result.roomInfoResponse;
}
- (HTTPResponse_Builder*) setRoomInfoResponse:(RoomInfoResponse*) value {
  result.hasRoomInfoResponse = YES;
  result.roomInfoResponse = value;
  return self;
}
- (HTTPResponse_Builder*) setRoomInfoResponseBuilder:(RoomInfoResponse_Builder*) builderForValue {
  return [self setRoomInfoResponse:[builderForValue build]];
}
- (HTTPResponse_Builder*) mergeRoomInfoResponse:(RoomInfoResponse*) value {
  if (result.hasRoomInfoResponse &&
      result.roomInfoResponse != [RoomInfoResponse defaultInstance]) {
    result.roomInfoResponse =
      [[[RoomInfoResponse builderWithPrototype:result.roomInfoResponse] mergeFrom:value] buildPartial];
  } else {
    result.roomInfoResponse = value;
  }
  result.hasRoomInfoResponse = YES;
  return self;
}
- (HTTPResponse_Builder*) clearRoomInfoResponse {
  result.hasRoomInfoResponse = NO;
  result.roomInfoResponse = [RoomInfoResponse defaultInstance];
  return self;
}
@end

