// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "RoomData.pb.h"

@implementation RoomDataRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [RoomDataRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface RoomInfo ()
@property int32_t roomId;
@property (retain) NSString* title;
@property (retain) NSString* ownerId;
@property (retain) NSString* ownerNickname;
@property int32_t type;
@property int32_t status;
@property (retain) NSString* picUrl;
@property int32_t genderType;
@property Float64 distance;
@property int32_t joinPersonCount;
@property int32_t limitPersonCount;
@property (retain) NSString* createTime;
@property (retain) NSString* beginTime;
@property (retain) Address* address;
@end

@implementation RoomInfo

- (BOOL) hasRoomId {
  return !!hasRoomId_;
}
- (void) setHasRoomId:(BOOL) value {
  hasRoomId_ = !!value;
}
@synthesize roomId;
- (BOOL) hasTitle {
  return !!hasTitle_;
}
- (void) setHasTitle:(BOOL) value {
  hasTitle_ = !!value;
}
@synthesize title;
- (BOOL) hasOwnerId {
  return !!hasOwnerId_;
}
- (void) setHasOwnerId:(BOOL) value {
  hasOwnerId_ = !!value;
}
@synthesize ownerId;
- (BOOL) hasOwnerNickname {
  return !!hasOwnerNickname_;
}
- (void) setHasOwnerNickname:(BOOL) value {
  hasOwnerNickname_ = !!value;
}
@synthesize ownerNickname;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) value {
  hasType_ = !!value;
}
@synthesize type;
- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value {
  hasStatus_ = !!value;
}
@synthesize status;
- (BOOL) hasPicUrl {
  return !!hasPicUrl_;
}
- (void) setHasPicUrl:(BOOL) value {
  hasPicUrl_ = !!value;
}
@synthesize picUrl;
- (BOOL) hasGenderType {
  return !!hasGenderType_;
}
- (void) setHasGenderType:(BOOL) value {
  hasGenderType_ = !!value;
}
@synthesize genderType;
- (BOOL) hasDistance {
  return !!hasDistance_;
}
- (void) setHasDistance:(BOOL) value {
  hasDistance_ = !!value;
}
@synthesize distance;
- (BOOL) hasJoinPersonCount {
  return !!hasJoinPersonCount_;
}
- (void) setHasJoinPersonCount:(BOOL) value {
  hasJoinPersonCount_ = !!value;
}
@synthesize joinPersonCount;
- (BOOL) hasLimitPersonCount {
  return !!hasLimitPersonCount_;
}
- (void) setHasLimitPersonCount:(BOOL) value {
  hasLimitPersonCount_ = !!value;
}
@synthesize limitPersonCount;
- (BOOL) hasCreateTime {
  return !!hasCreateTime_;
}
- (void) setHasCreateTime:(BOOL) value {
  hasCreateTime_ = !!value;
}
@synthesize createTime;
- (BOOL) hasBeginTime {
  return !!hasBeginTime_;
}
- (void) setHasBeginTime:(BOOL) value {
  hasBeginTime_ = !!value;
}
@synthesize beginTime;
- (BOOL) hasAddress {
  return !!hasAddress_;
}
- (void) setHasAddress:(BOOL) value {
  hasAddress_ = !!value;
}
@synthesize address;
- (void) dealloc {
  self.title = nil;
  self.ownerId = nil;
  self.ownerNickname = nil;
  self.picUrl = nil;
  self.createTime = nil;
  self.beginTime = nil;
  self.address = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.roomId = 0;
    self.title = @"";
    self.ownerId = @"";
    self.ownerNickname = @"";
    self.type = 0;
    self.status = 0;
    self.picUrl = @"";
    self.genderType = 0;
    self.distance = 0;
    self.joinPersonCount = 0;
    self.limitPersonCount = 0;
    self.createTime = @"";
    self.beginTime = @"";
    self.address = [Address defaultInstance];
  }
  return self;
}
static RoomInfo* defaultRoomInfoInstance = nil;
+ (void) initialize {
  if (self == [RoomInfo class]) {
    defaultRoomInfoInstance = [[RoomInfo alloc] init];
  }
}
+ (RoomInfo*) defaultInstance {
  return defaultRoomInfoInstance;
}
- (RoomInfo*) defaultInstance {
  return defaultRoomInfoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasRoomId) {
    [output writeInt32:1 value:self.roomId];
  }
  if (self.hasTitle) {
    [output writeString:2 value:self.title];
  }
  if (self.hasOwnerId) {
    [output writeString:3 value:self.ownerId];
  }
  if (self.hasOwnerNickname) {
    [output writeString:4 value:self.ownerNickname];
  }
  if (self.hasType) {
    [output writeInt32:5 value:self.type];
  }
  if (self.hasStatus) {
    [output writeInt32:6 value:self.status];
  }
  if (self.hasPicUrl) {
    [output writeString:7 value:self.picUrl];
  }
  if (self.hasGenderType) {
    [output writeInt32:8 value:self.genderType];
  }
  if (self.hasDistance) {
    [output writeDouble:9 value:self.distance];
  }
  if (self.hasJoinPersonCount) {
    [output writeInt32:10 value:self.joinPersonCount];
  }
  if (self.hasLimitPersonCount) {
    [output writeInt32:11 value:self.limitPersonCount];
  }
  if (self.hasCreateTime) {
    [output writeString:12 value:self.createTime];
  }
  if (self.hasBeginTime) {
    [output writeString:13 value:self.beginTime];
  }
  if (self.hasAddress) {
    [output writeMessage:14 value:self.address];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasRoomId) {
    size += computeInt32Size(1, self.roomId);
  }
  if (self.hasTitle) {
    size += computeStringSize(2, self.title);
  }
  if (self.hasOwnerId) {
    size += computeStringSize(3, self.ownerId);
  }
  if (self.hasOwnerNickname) {
    size += computeStringSize(4, self.ownerNickname);
  }
  if (self.hasType) {
    size += computeInt32Size(5, self.type);
  }
  if (self.hasStatus) {
    size += computeInt32Size(6, self.status);
  }
  if (self.hasPicUrl) {
    size += computeStringSize(7, self.picUrl);
  }
  if (self.hasGenderType) {
    size += computeInt32Size(8, self.genderType);
  }
  if (self.hasDistance) {
    size += computeDoubleSize(9, self.distance);
  }
  if (self.hasJoinPersonCount) {
    size += computeInt32Size(10, self.joinPersonCount);
  }
  if (self.hasLimitPersonCount) {
    size += computeInt32Size(11, self.limitPersonCount);
  }
  if (self.hasCreateTime) {
    size += computeStringSize(12, self.createTime);
  }
  if (self.hasBeginTime) {
    size += computeStringSize(13, self.beginTime);
  }
  if (self.hasAddress) {
    size += computeMessageSize(14, self.address);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (RoomInfo*) parseFromData:(NSData*) data {
  return (RoomInfo*)[[[RoomInfo builder] mergeFromData:data] build];
}
+ (RoomInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RoomInfo*)[[[RoomInfo builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RoomInfo*) parseFromInputStream:(NSInputStream*) input {
  return (RoomInfo*)[[[RoomInfo builder] mergeFromInputStream:input] build];
}
+ (RoomInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RoomInfo*)[[[RoomInfo builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RoomInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RoomInfo*)[[[RoomInfo builder] mergeFromCodedInputStream:input] build];
}
+ (RoomInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RoomInfo*)[[[RoomInfo builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RoomInfo_Builder*) builder {
  return [[[RoomInfo_Builder alloc] init] autorelease];
}
+ (RoomInfo_Builder*) builderWithPrototype:(RoomInfo*) prototype {
  return [[RoomInfo builder] mergeFrom:prototype];
}
- (RoomInfo_Builder*) builder {
  return [RoomInfo builder];
}
@end

@interface RoomInfo_Builder()
@property (retain) RoomInfo* result;
@end

@implementation RoomInfo_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[RoomInfo alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (RoomInfo_Builder*) clear {
  self.result = [[[RoomInfo alloc] init] autorelease];
  return self;
}
- (RoomInfo_Builder*) clone {
  return [RoomInfo builderWithPrototype:result];
}
- (RoomInfo*) defaultInstance {
  return [RoomInfo defaultInstance];
}
- (RoomInfo*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RoomInfo*) buildPartial {
  RoomInfo* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (RoomInfo_Builder*) mergeFrom:(RoomInfo*) other {
  if (other == [RoomInfo defaultInstance]) {
    return self;
  }
  if (other.hasRoomId) {
    [self setRoomId:other.roomId];
  }
  if (other.hasTitle) {
    [self setTitle:other.title];
  }
  if (other.hasOwnerId) {
    [self setOwnerId:other.ownerId];
  }
  if (other.hasOwnerNickname) {
    [self setOwnerNickname:other.ownerNickname];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  if (other.hasPicUrl) {
    [self setPicUrl:other.picUrl];
  }
  if (other.hasGenderType) {
    [self setGenderType:other.genderType];
  }
  if (other.hasDistance) {
    [self setDistance:other.distance];
  }
  if (other.hasJoinPersonCount) {
    [self setJoinPersonCount:other.joinPersonCount];
  }
  if (other.hasLimitPersonCount) {
    [self setLimitPersonCount:other.limitPersonCount];
  }
  if (other.hasCreateTime) {
    [self setCreateTime:other.createTime];
  }
  if (other.hasBeginTime) {
    [self setBeginTime:other.beginTime];
  }
  if (other.hasAddress) {
    [self mergeAddress:other.address];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RoomInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RoomInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setRoomId:[input readInt32]];
        break;
      }
      case 18: {
        [self setTitle:[input readString]];
        break;
      }
      case 26: {
        [self setOwnerId:[input readString]];
        break;
      }
      case 34: {
        [self setOwnerNickname:[input readString]];
        break;
      }
      case 40: {
        [self setType:[input readInt32]];
        break;
      }
      case 48: {
        [self setStatus:[input readInt32]];
        break;
      }
      case 58: {
        [self setPicUrl:[input readString]];
        break;
      }
      case 64: {
        [self setGenderType:[input readInt32]];
        break;
      }
      case 73: {
        [self setDistance:[input readDouble]];
        break;
      }
      case 80: {
        [self setJoinPersonCount:[input readInt32]];
        break;
      }
      case 88: {
        [self setLimitPersonCount:[input readInt32]];
        break;
      }
      case 98: {
        [self setCreateTime:[input readString]];
        break;
      }
      case 106: {
        [self setBeginTime:[input readString]];
        break;
      }
      case 114: {
        Address_Builder* subBuilder = [Address builder];
        if (self.hasAddress) {
          [subBuilder mergeFrom:self.address];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setAddress:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasRoomId {
  return result.hasRoomId;
}
- (int32_t) roomId {
  return result.roomId;
}
- (RoomInfo_Builder*) setRoomId:(int32_t) value {
  result.hasRoomId = YES;
  result.roomId = value;
  return self;
}
- (RoomInfo_Builder*) clearRoomId {
  result.hasRoomId = NO;
  result.roomId = 0;
  return self;
}
- (BOOL) hasTitle {
  return result.hasTitle;
}
- (NSString*) title {
  return result.title;
}
- (RoomInfo_Builder*) setTitle:(NSString*) value {
  result.hasTitle = YES;
  result.title = value;
  return self;
}
- (RoomInfo_Builder*) clearTitle {
  result.hasTitle = NO;
  result.title = @"";
  return self;
}
- (BOOL) hasOwnerId {
  return result.hasOwnerId;
}
- (NSString*) ownerId {
  return result.ownerId;
}
- (RoomInfo_Builder*) setOwnerId:(NSString*) value {
  result.hasOwnerId = YES;
  result.ownerId = value;
  return self;
}
- (RoomInfo_Builder*) clearOwnerId {
  result.hasOwnerId = NO;
  result.ownerId = @"";
  return self;
}
- (BOOL) hasOwnerNickname {
  return result.hasOwnerNickname;
}
- (NSString*) ownerNickname {
  return result.ownerNickname;
}
- (RoomInfo_Builder*) setOwnerNickname:(NSString*) value {
  result.hasOwnerNickname = YES;
  result.ownerNickname = value;
  return self;
}
- (RoomInfo_Builder*) clearOwnerNickname {
  result.hasOwnerNickname = NO;
  result.ownerNickname = @"";
  return self;
}
- (BOOL) hasType {
  return result.hasType;
}
- (int32_t) type {
  return result.type;
}
- (RoomInfo_Builder*) setType:(int32_t) value {
  result.hasType = YES;
  result.type = value;
  return self;
}
- (RoomInfo_Builder*) clearType {
  result.hasType = NO;
  result.type = 0;
  return self;
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (int32_t) status {
  return result.status;
}
- (RoomInfo_Builder*) setStatus:(int32_t) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (RoomInfo_Builder*) clearStatus {
  result.hasStatus = NO;
  result.status = 0;
  return self;
}
- (BOOL) hasPicUrl {
  return result.hasPicUrl;
}
- (NSString*) picUrl {
  return result.picUrl;
}
- (RoomInfo_Builder*) setPicUrl:(NSString*) value {
  result.hasPicUrl = YES;
  result.picUrl = value;
  return self;
}
- (RoomInfo_Builder*) clearPicUrl {
  result.hasPicUrl = NO;
  result.picUrl = @"";
  return self;
}
- (BOOL) hasGenderType {
  return result.hasGenderType;
}
- (int32_t) genderType {
  return result.genderType;
}
- (RoomInfo_Builder*) setGenderType:(int32_t) value {
  result.hasGenderType = YES;
  result.genderType = value;
  return self;
}
- (RoomInfo_Builder*) clearGenderType {
  result.hasGenderType = NO;
  result.genderType = 0;
  return self;
}
- (BOOL) hasDistance {
  return result.hasDistance;
}
- (Float64) distance {
  return result.distance;
}
- (RoomInfo_Builder*) setDistance:(Float64) value {
  result.hasDistance = YES;
  result.distance = value;
  return self;
}
- (RoomInfo_Builder*) clearDistance {
  result.hasDistance = NO;
  result.distance = 0;
  return self;
}
- (BOOL) hasJoinPersonCount {
  return result.hasJoinPersonCount;
}
- (int32_t) joinPersonCount {
  return result.joinPersonCount;
}
- (RoomInfo_Builder*) setJoinPersonCount:(int32_t) value {
  result.hasJoinPersonCount = YES;
  result.joinPersonCount = value;
  return self;
}
- (RoomInfo_Builder*) clearJoinPersonCount {
  result.hasJoinPersonCount = NO;
  result.joinPersonCount = 0;
  return self;
}
- (BOOL) hasLimitPersonCount {
  return result.hasLimitPersonCount;
}
- (int32_t) limitPersonCount {
  return result.limitPersonCount;
}
- (RoomInfo_Builder*) setLimitPersonCount:(int32_t) value {
  result.hasLimitPersonCount = YES;
  result.limitPersonCount = value;
  return self;
}
- (RoomInfo_Builder*) clearLimitPersonCount {
  result.hasLimitPersonCount = NO;
  result.limitPersonCount = 0;
  return self;
}
- (BOOL) hasCreateTime {
  return result.hasCreateTime;
}
- (NSString*) createTime {
  return result.createTime;
}
- (RoomInfo_Builder*) setCreateTime:(NSString*) value {
  result.hasCreateTime = YES;
  result.createTime = value;
  return self;
}
- (RoomInfo_Builder*) clearCreateTime {
  result.hasCreateTime = NO;
  result.createTime = @"";
  return self;
}
- (BOOL) hasBeginTime {
  return result.hasBeginTime;
}
- (NSString*) beginTime {
  return result.beginTime;
}
- (RoomInfo_Builder*) setBeginTime:(NSString*) value {
  result.hasBeginTime = YES;
  result.beginTime = value;
  return self;
}
- (RoomInfo_Builder*) clearBeginTime {
  result.hasBeginTime = NO;
  result.beginTime = @"";
  return self;
}
- (BOOL) hasAddress {
  return result.hasAddress;
}
- (Address*) address {
  return result.address;
}
- (RoomInfo_Builder*) setAddress:(Address*) value {
  result.hasAddress = YES;
  result.address = value;
  return self;
}
- (RoomInfo_Builder*) setAddressBuilder:(Address_Builder*) builderForValue {
  return [self setAddress:[builderForValue build]];
}
- (RoomInfo_Builder*) mergeAddress:(Address*) value {
  if (result.hasAddress &&
      result.address != [Address defaultInstance]) {
    result.address =
      [[[Address builderWithPrototype:result.address] mergeFrom:value] buildPartial];
  } else {
    result.address = value;
  }
  result.hasAddress = YES;
  return self;
}
- (RoomInfo_Builder*) clearAddress {
  result.hasAddress = NO;
  result.address = [Address defaultInstance];
  return self;
}
@end

@interface Address ()
@property int32_t addrType;
@property Float64 longitude;
@property Float64 latitude;
@property (retain) NSString* detailAddr;
@property (retain) NSString* addrRemark;
@end

@implementation Address

- (BOOL) hasAddrType {
  return !!hasAddrType_;
}
- (void) setHasAddrType:(BOOL) value {
  hasAddrType_ = !!value;
}
@synthesize addrType;
- (BOOL) hasLongitude {
  return !!hasLongitude_;
}
- (void) setHasLongitude:(BOOL) value {
  hasLongitude_ = !!value;
}
@synthesize longitude;
- (BOOL) hasLatitude {
  return !!hasLatitude_;
}
- (void) setHasLatitude:(BOOL) value {
  hasLatitude_ = !!value;
}
@synthesize latitude;
- (BOOL) hasDetailAddr {
  return !!hasDetailAddr_;
}
- (void) setHasDetailAddr:(BOOL) value {
  hasDetailAddr_ = !!value;
}
@synthesize detailAddr;
- (BOOL) hasAddrRemark {
  return !!hasAddrRemark_;
}
- (void) setHasAddrRemark:(BOOL) value {
  hasAddrRemark_ = !!value;
}
@synthesize addrRemark;
- (void) dealloc {
  self.detailAddr = nil;
  self.addrRemark = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.addrType = 0;
    self.longitude = 0;
    self.latitude = 0;
    self.detailAddr = @"";
    self.addrRemark = @"";
  }
  return self;
}
static Address* defaultAddressInstance = nil;
+ (void) initialize {
  if (self == [Address class]) {
    defaultAddressInstance = [[Address alloc] init];
  }
}
+ (Address*) defaultInstance {
  return defaultAddressInstance;
}
- (Address*) defaultInstance {
  return defaultAddressInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasAddrType) {
    [output writeInt32:1 value:self.addrType];
  }
  if (self.hasLongitude) {
    [output writeDouble:2 value:self.longitude];
  }
  if (self.hasLatitude) {
    [output writeDouble:3 value:self.latitude];
  }
  if (self.hasDetailAddr) {
    [output writeString:4 value:self.detailAddr];
  }
  if (self.hasAddrRemark) {
    [output writeString:5 value:self.addrRemark];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasAddrType) {
    size += computeInt32Size(1, self.addrType);
  }
  if (self.hasLongitude) {
    size += computeDoubleSize(2, self.longitude);
  }
  if (self.hasLatitude) {
    size += computeDoubleSize(3, self.latitude);
  }
  if (self.hasDetailAddr) {
    size += computeStringSize(4, self.detailAddr);
  }
  if (self.hasAddrRemark) {
    size += computeStringSize(5, self.addrRemark);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Address*) parseFromData:(NSData*) data {
  return (Address*)[[[Address builder] mergeFromData:data] build];
}
+ (Address*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Address*)[[[Address builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Address*) parseFromInputStream:(NSInputStream*) input {
  return (Address*)[[[Address builder] mergeFromInputStream:input] build];
}
+ (Address*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Address*)[[[Address builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Address*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Address*)[[[Address builder] mergeFromCodedInputStream:input] build];
}
+ (Address*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Address*)[[[Address builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Address_Builder*) builder {
  return [[[Address_Builder alloc] init] autorelease];
}
+ (Address_Builder*) builderWithPrototype:(Address*) prototype {
  return [[Address builder] mergeFrom:prototype];
}
- (Address_Builder*) builder {
  return [Address builder];
}
@end

@interface Address_Builder()
@property (retain) Address* result;
@end

@implementation Address_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Address alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Address_Builder*) clear {
  self.result = [[[Address alloc] init] autorelease];
  return self;
}
- (Address_Builder*) clone {
  return [Address builderWithPrototype:result];
}
- (Address*) defaultInstance {
  return [Address defaultInstance];
}
- (Address*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Address*) buildPartial {
  Address* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Address_Builder*) mergeFrom:(Address*) other {
  if (other == [Address defaultInstance]) {
    return self;
  }
  if (other.hasAddrType) {
    [self setAddrType:other.addrType];
  }
  if (other.hasLongitude) {
    [self setLongitude:other.longitude];
  }
  if (other.hasLatitude) {
    [self setLatitude:other.latitude];
  }
  if (other.hasDetailAddr) {
    [self setDetailAddr:other.detailAddr];
  }
  if (other.hasAddrRemark) {
    [self setAddrRemark:other.addrRemark];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Address_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Address_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setAddrType:[input readInt32]];
        break;
      }
      case 17: {
        [self setLongitude:[input readDouble]];
        break;
      }
      case 25: {
        [self setLatitude:[input readDouble]];
        break;
      }
      case 34: {
        [self setDetailAddr:[input readString]];
        break;
      }
      case 42: {
        [self setAddrRemark:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasAddrType {
  return result.hasAddrType;
}
- (int32_t) addrType {
  return result.addrType;
}
- (Address_Builder*) setAddrType:(int32_t) value {
  result.hasAddrType = YES;
  result.addrType = value;
  return self;
}
- (Address_Builder*) clearAddrType {
  result.hasAddrType = NO;
  result.addrType = 0;
  return self;
}
- (BOOL) hasLongitude {
  return result.hasLongitude;
}
- (Float64) longitude {
  return result.longitude;
}
- (Address_Builder*) setLongitude:(Float64) value {
  result.hasLongitude = YES;
  result.longitude = value;
  return self;
}
- (Address_Builder*) clearLongitude {
  result.hasLongitude = NO;
  result.longitude = 0;
  return self;
}
- (BOOL) hasLatitude {
  return result.hasLatitude;
}
- (Float64) latitude {
  return result.latitude;
}
- (Address_Builder*) setLatitude:(Float64) value {
  result.hasLatitude = YES;
  result.latitude = value;
  return self;
}
- (Address_Builder*) clearLatitude {
  result.hasLatitude = NO;
  result.latitude = 0;
  return self;
}
- (BOOL) hasDetailAddr {
  return result.hasDetailAddr;
}
- (NSString*) detailAddr {
  return result.detailAddr;
}
- (Address_Builder*) setDetailAddr:(NSString*) value {
  result.hasDetailAddr = YES;
  result.detailAddr = value;
  return self;
}
- (Address_Builder*) clearDetailAddr {
  result.hasDetailAddr = NO;
  result.detailAddr = @"";
  return self;
}
- (BOOL) hasAddrRemark {
  return result.hasAddrRemark;
}
- (NSString*) addrRemark {
  return result.addrRemark;
}
- (Address_Builder*) setAddrRemark:(NSString*) value {
  result.hasAddrRemark = YES;
  result.addrRemark = value;
  return self;
}
- (Address_Builder*) clearAddrRemark {
  result.hasAddrRemark = NO;
  result.addrRemark = @"";
  return self;
}
@end

