// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Address;
@class Address_Builder;
@class RoomInfo;
@class RoomInfo_Builder;

@interface RoomDataRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface RoomInfo : PBGeneratedMessage {
@private
  BOOL hasDistance_:1;
  BOOL hasRoomId_:1;
  BOOL hasOwnerId_:1;
  BOOL hasType_:1;
  BOOL hasStatus_:1;
  BOOL hasPicId_:1;
  BOOL hasGenderType_:1;
  BOOL hasJoinPersonCount_:1;
  BOOL hasLimitPersonCount_:1;
  BOOL hasRecordId_:1;
  BOOL hasTitle_:1;
  BOOL hasOwnerNickname_:1;
  BOOL hasCreateTime_:1;
  BOOL hasBeginTime_:1;
  BOOL hasAddress_:1;
  Float64 distance;
  int32_t roomId;
  int32_t ownerId;
  int32_t type;
  int32_t status;
  int32_t picId;
  int32_t genderType;
  int32_t joinPersonCount;
  int32_t limitPersonCount;
  int32_t recordId;
  NSString* title;
  NSString* ownerNickname;
  NSString* createTime;
  NSString* beginTime;
  Address* address;
}
- (BOOL) hasRoomId;
- (BOOL) hasTitle;
- (BOOL) hasOwnerId;
- (BOOL) hasOwnerNickname;
- (BOOL) hasType;
- (BOOL) hasStatus;
- (BOOL) hasPicId;
- (BOOL) hasGenderType;
- (BOOL) hasDistance;
- (BOOL) hasJoinPersonCount;
- (BOOL) hasLimitPersonCount;
- (BOOL) hasRecordId;
- (BOOL) hasCreateTime;
- (BOOL) hasBeginTime;
- (BOOL) hasAddress;
@property (readonly) int32_t roomId;
@property (readonly, retain) NSString* title;
@property (readonly) int32_t ownerId;
@property (readonly, retain) NSString* ownerNickname;
@property (readonly) int32_t type;
@property (readonly) int32_t status;
@property (readonly) int32_t picId;
@property (readonly) int32_t genderType;
@property (readonly) Float64 distance;
@property (readonly) int32_t joinPersonCount;
@property (readonly) int32_t limitPersonCount;
@property (readonly) int32_t recordId;
@property (readonly, retain) NSString* createTime;
@property (readonly, retain) NSString* beginTime;
@property (readonly, retain) Address* address;

+ (RoomInfo*) defaultInstance;
- (RoomInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RoomInfo_Builder*) builder;
+ (RoomInfo_Builder*) builder;
+ (RoomInfo_Builder*) builderWithPrototype:(RoomInfo*) prototype;

+ (RoomInfo*) parseFromData:(NSData*) data;
+ (RoomInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomInfo*) parseFromInputStream:(NSInputStream*) input;
+ (RoomInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RoomInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RoomInfo_Builder : PBGeneratedMessage_Builder {
@private
  RoomInfo* result;
}

- (RoomInfo*) defaultInstance;

- (RoomInfo_Builder*) clear;
- (RoomInfo_Builder*) clone;

- (RoomInfo*) build;
- (RoomInfo*) buildPartial;

- (RoomInfo_Builder*) mergeFrom:(RoomInfo*) other;
- (RoomInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RoomInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRoomId;
- (int32_t) roomId;
- (RoomInfo_Builder*) setRoomId:(int32_t) value;
- (RoomInfo_Builder*) clearRoomId;

- (BOOL) hasTitle;
- (NSString*) title;
- (RoomInfo_Builder*) setTitle:(NSString*) value;
- (RoomInfo_Builder*) clearTitle;

- (BOOL) hasOwnerId;
- (int32_t) ownerId;
- (RoomInfo_Builder*) setOwnerId:(int32_t) value;
- (RoomInfo_Builder*) clearOwnerId;

- (BOOL) hasOwnerNickname;
- (NSString*) ownerNickname;
- (RoomInfo_Builder*) setOwnerNickname:(NSString*) value;
- (RoomInfo_Builder*) clearOwnerNickname;

- (BOOL) hasType;
- (int32_t) type;
- (RoomInfo_Builder*) setType:(int32_t) value;
- (RoomInfo_Builder*) clearType;

- (BOOL) hasStatus;
- (int32_t) status;
- (RoomInfo_Builder*) setStatus:(int32_t) value;
- (RoomInfo_Builder*) clearStatus;

- (BOOL) hasPicId;
- (int32_t) picId;
- (RoomInfo_Builder*) setPicId:(int32_t) value;
- (RoomInfo_Builder*) clearPicId;

- (BOOL) hasGenderType;
- (int32_t) genderType;
- (RoomInfo_Builder*) setGenderType:(int32_t) value;
- (RoomInfo_Builder*) clearGenderType;

- (BOOL) hasDistance;
- (Float64) distance;
- (RoomInfo_Builder*) setDistance:(Float64) value;
- (RoomInfo_Builder*) clearDistance;

- (BOOL) hasJoinPersonCount;
- (int32_t) joinPersonCount;
- (RoomInfo_Builder*) setJoinPersonCount:(int32_t) value;
- (RoomInfo_Builder*) clearJoinPersonCount;

- (BOOL) hasLimitPersonCount;
- (int32_t) limitPersonCount;
- (RoomInfo_Builder*) setLimitPersonCount:(int32_t) value;
- (RoomInfo_Builder*) clearLimitPersonCount;

- (BOOL) hasRecordId;
- (int32_t) recordId;
- (RoomInfo_Builder*) setRecordId:(int32_t) value;
- (RoomInfo_Builder*) clearRecordId;

- (BOOL) hasCreateTime;
- (NSString*) createTime;
- (RoomInfo_Builder*) setCreateTime:(NSString*) value;
- (RoomInfo_Builder*) clearCreateTime;

- (BOOL) hasBeginTime;
- (NSString*) beginTime;
- (RoomInfo_Builder*) setBeginTime:(NSString*) value;
- (RoomInfo_Builder*) clearBeginTime;

- (BOOL) hasAddress;
- (Address*) address;
- (RoomInfo_Builder*) setAddress:(Address*) value;
- (RoomInfo_Builder*) setAddressBuilder:(Address_Builder*) builderForValue;
- (RoomInfo_Builder*) mergeAddress:(Address*) value;
- (RoomInfo_Builder*) clearAddress;
@end

@interface Address : PBGeneratedMessage {
@private
  BOOL hasLongitude_:1;
  BOOL hasLatitude_:1;
  BOOL hasAddrType_:1;
  BOOL hasDetailAddr_:1;
  BOOL hasAddrRemark_:1;
  Float64 longitude;
  Float64 latitude;
  int32_t addrType;
  NSString* detailAddr;
  NSString* addrRemark;
}
- (BOOL) hasAddrType;
- (BOOL) hasLongitude;
- (BOOL) hasLatitude;
- (BOOL) hasDetailAddr;
- (BOOL) hasAddrRemark;
@property (readonly) int32_t addrType;
@property (readonly) Float64 longitude;
@property (readonly) Float64 latitude;
@property (readonly, retain) NSString* detailAddr;
@property (readonly, retain) NSString* addrRemark;

+ (Address*) defaultInstance;
- (Address*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Address_Builder*) builder;
+ (Address_Builder*) builder;
+ (Address_Builder*) builderWithPrototype:(Address*) prototype;

+ (Address*) parseFromData:(NSData*) data;
+ (Address*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Address*) parseFromInputStream:(NSInputStream*) input;
+ (Address*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Address*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Address*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Address_Builder : PBGeneratedMessage_Builder {
@private
  Address* result;
}

- (Address*) defaultInstance;

- (Address_Builder*) clear;
- (Address_Builder*) clone;

- (Address*) build;
- (Address*) buildPartial;

- (Address_Builder*) mergeFrom:(Address*) other;
- (Address_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Address_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAddrType;
- (int32_t) addrType;
- (Address_Builder*) setAddrType:(int32_t) value;
- (Address_Builder*) clearAddrType;

- (BOOL) hasLongitude;
- (Float64) longitude;
- (Address_Builder*) setLongitude:(Float64) value;
- (Address_Builder*) clearLongitude;

- (BOOL) hasLatitude;
- (Float64) latitude;
- (Address_Builder*) setLatitude:(Float64) value;
- (Address_Builder*) clearLatitude;

- (BOOL) hasDetailAddr;
- (NSString*) detailAddr;
- (Address_Builder*) setDetailAddr:(NSString*) value;
- (Address_Builder*) clearDetailAddr;

- (BOOL) hasAddrRemark;
- (NSString*) addrRemark;
- (Address_Builder*) setAddrRemark:(NSString*) value;
- (Address_Builder*) clearAddrRemark;
@end

