// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "MessageData.pb.h"

@implementation MessageDataRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [MessageDataRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface Message_Info ()
@property int32_t messageId;
@property int32_t senderId;
@property int32_t recipientId;
@property int32_t type;
@property (retain) NSString* content;
@property (retain) NSString* title;
@property int32_t fileId;
@property int32_t roomId;
@property (retain) NSString* time;
@property BOOL status;
@end

@implementation Message_Info

- (BOOL) hasMessageId {
  return !!hasMessageId_;
}
- (void) setHasMessageId:(BOOL) value {
  hasMessageId_ = !!value;
}
@synthesize messageId;
- (BOOL) hasSenderId {
  return !!hasSenderId_;
}
- (void) setHasSenderId:(BOOL) value {
  hasSenderId_ = !!value;
}
@synthesize senderId;
- (BOOL) hasRecipientId {
  return !!hasRecipientId_;
}
- (void) setHasRecipientId:(BOOL) value {
  hasRecipientId_ = !!value;
}
@synthesize recipientId;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) value {
  hasType_ = !!value;
}
@synthesize type;
- (BOOL) hasContent {
  return !!hasContent_;
}
- (void) setHasContent:(BOOL) value {
  hasContent_ = !!value;
}
@synthesize content;
- (BOOL) hasTitle {
  return !!hasTitle_;
}
- (void) setHasTitle:(BOOL) value {
  hasTitle_ = !!value;
}
@synthesize title;
- (BOOL) hasFileId {
  return !!hasFileId_;
}
- (void) setHasFileId:(BOOL) value {
  hasFileId_ = !!value;
}
@synthesize fileId;
- (BOOL) hasRoomId {
  return !!hasRoomId_;
}
- (void) setHasRoomId:(BOOL) value {
  hasRoomId_ = !!value;
}
@synthesize roomId;
- (BOOL) hasTime {
  return !!hasTime_;
}
- (void) setHasTime:(BOOL) value {
  hasTime_ = !!value;
}
@synthesize time;
- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value {
  hasStatus_ = !!value;
}
- (BOOL) status {
  return !!status_;
}
- (void) setStatus:(BOOL) value {
  status_ = !!value;
}
- (void) dealloc {
  self.content = nil;
  self.title = nil;
  self.time = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.messageId = 0;
    self.senderId = 0;
    self.recipientId = 0;
    self.type = 0;
    self.content = @"";
    self.title = @"";
    self.fileId = 0;
    self.roomId = 0;
    self.time = @"";
    self.status = NO;
  }
  return self;
}
static Message_Info* defaultMessage_InfoInstance = nil;
+ (void) initialize {
  if (self == [Message_Info class]) {
    defaultMessage_InfoInstance = [[Message_Info alloc] init];
  }
}
+ (Message_Info*) defaultInstance {
  return defaultMessage_InfoInstance;
}
- (Message_Info*) defaultInstance {
  return defaultMessage_InfoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasMessageId) {
    [output writeInt32:1 value:self.messageId];
  }
  if (self.hasSenderId) {
    [output writeInt32:2 value:self.senderId];
  }
  if (self.hasRecipientId) {
    [output writeInt32:3 value:self.recipientId];
  }
  if (self.hasType) {
    [output writeInt32:4 value:self.type];
  }
  if (self.hasContent) {
    [output writeString:5 value:self.content];
  }
  if (self.hasTitle) {
    [output writeString:6 value:self.title];
  }
  if (self.hasFileId) {
    [output writeInt32:7 value:self.fileId];
  }
  if (self.hasRoomId) {
    [output writeInt32:8 value:self.roomId];
  }
  if (self.hasTime) {
    [output writeString:9 value:self.time];
  }
  if (self.hasStatus) {
    [output writeBool:10 value:self.status];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasMessageId) {
    size += computeInt32Size(1, self.messageId);
  }
  if (self.hasSenderId) {
    size += computeInt32Size(2, self.senderId);
  }
  if (self.hasRecipientId) {
    size += computeInt32Size(3, self.recipientId);
  }
  if (self.hasType) {
    size += computeInt32Size(4, self.type);
  }
  if (self.hasContent) {
    size += computeStringSize(5, self.content);
  }
  if (self.hasTitle) {
    size += computeStringSize(6, self.title);
  }
  if (self.hasFileId) {
    size += computeInt32Size(7, self.fileId);
  }
  if (self.hasRoomId) {
    size += computeInt32Size(8, self.roomId);
  }
  if (self.hasTime) {
    size += computeStringSize(9, self.time);
  }
  if (self.hasStatus) {
    size += computeBoolSize(10, self.status);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Message_Info*) parseFromData:(NSData*) data {
  return (Message_Info*)[[[Message_Info builder] mergeFromData:data] build];
}
+ (Message_Info*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_Info*)[[[Message_Info builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Message_Info*) parseFromInputStream:(NSInputStream*) input {
  return (Message_Info*)[[[Message_Info builder] mergeFromInputStream:input] build];
}
+ (Message_Info*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_Info*)[[[Message_Info builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_Info*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Message_Info*)[[[Message_Info builder] mergeFromCodedInputStream:input] build];
}
+ (Message_Info*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_Info*)[[[Message_Info builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_Info_Builder*) builder {
  return [[[Message_Info_Builder alloc] init] autorelease];
}
+ (Message_Info_Builder*) builderWithPrototype:(Message_Info*) prototype {
  return [[Message_Info builder] mergeFrom:prototype];
}
- (Message_Info_Builder*) builder {
  return [Message_Info builder];
}
@end

@interface Message_Info_Builder()
@property (retain) Message_Info* result;
@end

@implementation Message_Info_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Message_Info alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Message_Info_Builder*) clear {
  self.result = [[[Message_Info alloc] init] autorelease];
  return self;
}
- (Message_Info_Builder*) clone {
  return [Message_Info builderWithPrototype:result];
}
- (Message_Info*) defaultInstance {
  return [Message_Info defaultInstance];
}
- (Message_Info*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Message_Info*) buildPartial {
  Message_Info* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Message_Info_Builder*) mergeFrom:(Message_Info*) other {
  if (other == [Message_Info defaultInstance]) {
    return self;
  }
  if (other.hasMessageId) {
    [self setMessageId:other.messageId];
  }
  if (other.hasSenderId) {
    [self setSenderId:other.senderId];
  }
  if (other.hasRecipientId) {
    [self setRecipientId:other.recipientId];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  if (other.hasContent) {
    [self setContent:other.content];
  }
  if (other.hasTitle) {
    [self setTitle:other.title];
  }
  if (other.hasFileId) {
    [self setFileId:other.fileId];
  }
  if (other.hasRoomId) {
    [self setRoomId:other.roomId];
  }
  if (other.hasTime) {
    [self setTime:other.time];
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Message_Info_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Message_Info_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setMessageId:[input readInt32]];
        break;
      }
      case 16: {
        [self setSenderId:[input readInt32]];
        break;
      }
      case 24: {
        [self setRecipientId:[input readInt32]];
        break;
      }
      case 32: {
        [self setType:[input readInt32]];
        break;
      }
      case 42: {
        [self setContent:[input readString]];
        break;
      }
      case 50: {
        [self setTitle:[input readString]];
        break;
      }
      case 56: {
        [self setFileId:[input readInt32]];
        break;
      }
      case 64: {
        [self setRoomId:[input readInt32]];
        break;
      }
      case 74: {
        [self setTime:[input readString]];
        break;
      }
      case 80: {
        [self setStatus:[input readBool]];
        break;
      }
    }
  }
}
- (BOOL) hasMessageId {
  return result.hasMessageId;
}
- (int32_t) messageId {
  return result.messageId;
}
- (Message_Info_Builder*) setMessageId:(int32_t) value {
  result.hasMessageId = YES;
  result.messageId = value;
  return self;
}
- (Message_Info_Builder*) clearMessageId {
  result.hasMessageId = NO;
  result.messageId = 0;
  return self;
}
- (BOOL) hasSenderId {
  return result.hasSenderId;
}
- (int32_t) senderId {
  return result.senderId;
}
- (Message_Info_Builder*) setSenderId:(int32_t) value {
  result.hasSenderId = YES;
  result.senderId = value;
  return self;
}
- (Message_Info_Builder*) clearSenderId {
  result.hasSenderId = NO;
  result.senderId = 0;
  return self;
}
- (BOOL) hasRecipientId {
  return result.hasRecipientId;
}
- (int32_t) recipientId {
  return result.recipientId;
}
- (Message_Info_Builder*) setRecipientId:(int32_t) value {
  result.hasRecipientId = YES;
  result.recipientId = value;
  return self;
}
- (Message_Info_Builder*) clearRecipientId {
  result.hasRecipientId = NO;
  result.recipientId = 0;
  return self;
}
- (BOOL) hasType {
  return result.hasType;
}
- (int32_t) type {
  return result.type;
}
- (Message_Info_Builder*) setType:(int32_t) value {
  result.hasType = YES;
  result.type = value;
  return self;
}
- (Message_Info_Builder*) clearType {
  result.hasType = NO;
  result.type = 0;
  return self;
}
- (BOOL) hasContent {
  return result.hasContent;
}
- (NSString*) content {
  return result.content;
}
- (Message_Info_Builder*) setContent:(NSString*) value {
  result.hasContent = YES;
  result.content = value;
  return self;
}
- (Message_Info_Builder*) clearContent {
  result.hasContent = NO;
  result.content = @"";
  return self;
}
- (BOOL) hasTitle {
  return result.hasTitle;
}
- (NSString*) title {
  return result.title;
}
- (Message_Info_Builder*) setTitle:(NSString*) value {
  result.hasTitle = YES;
  result.title = value;
  return self;
}
- (Message_Info_Builder*) clearTitle {
  result.hasTitle = NO;
  result.title = @"";
  return self;
}
- (BOOL) hasFileId {
  return result.hasFileId;
}
- (int32_t) fileId {
  return result.fileId;
}
- (Message_Info_Builder*) setFileId:(int32_t) value {
  result.hasFileId = YES;
  result.fileId = value;
  return self;
}
- (Message_Info_Builder*) clearFileId {
  result.hasFileId = NO;
  result.fileId = 0;
  return self;
}
- (BOOL) hasRoomId {
  return result.hasRoomId;
}
- (int32_t) roomId {
  return result.roomId;
}
- (Message_Info_Builder*) setRoomId:(int32_t) value {
  result.hasRoomId = YES;
  result.roomId = value;
  return self;
}
- (Message_Info_Builder*) clearRoomId {
  result.hasRoomId = NO;
  result.roomId = 0;
  return self;
}
- (BOOL) hasTime {
  return result.hasTime;
}
- (NSString*) time {
  return result.time;
}
- (Message_Info_Builder*) setTime:(NSString*) value {
  result.hasTime = YES;
  result.time = value;
  return self;
}
- (Message_Info_Builder*) clearTime {
  result.hasTime = NO;
  result.time = @"";
  return self;
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (BOOL) status {
  return result.status;
}
- (Message_Info_Builder*) setStatus:(BOOL) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (Message_Info_Builder*) clearStatus {
  result.hasStatus = NO;
  result.status = NO;
  return self;
}
@end

