// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Message_Info;
@class Message_Info_Builder;

@interface MessageDataRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Message_Info : PBGeneratedMessage {
@private
  BOOL hasMessageId_:1;
  BOOL hasSenderId_:1;
  BOOL hasRecipientId_:1;
  BOOL hasType_:1;
  BOOL hasFileId_:1;
  BOOL hasRoomId_:1;
  BOOL hasContent_:1;
  BOOL hasTitle_:1;
  BOOL hasTime_:1;
  int32_t messageId;
  int32_t senderId;
  int32_t recipientId;
  int32_t type;
  int32_t fileId;
  int32_t roomId;
  NSString* content;
  NSString* title;
  NSString* time;
}
- (BOOL) hasMessageId;
- (BOOL) hasSenderId;
- (BOOL) hasRecipientId;
- (BOOL) hasType;
- (BOOL) hasContent;
- (BOOL) hasTitle;
- (BOOL) hasFileId;
- (BOOL) hasRoomId;
- (BOOL) hasTime;
@property (readonly) int32_t messageId;
@property (readonly) int32_t senderId;
@property (readonly) int32_t recipientId;
@property (readonly) int32_t type;
@property (readonly, retain) NSString* content;
@property (readonly, retain) NSString* title;
@property (readonly) int32_t fileId;
@property (readonly) int32_t roomId;
@property (readonly, retain) NSString* time;

+ (Message_Info*) defaultInstance;
- (Message_Info*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_Info_Builder*) builder;
+ (Message_Info_Builder*) builder;
+ (Message_Info_Builder*) builderWithPrototype:(Message_Info*) prototype;

+ (Message_Info*) parseFromData:(NSData*) data;
+ (Message_Info*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_Info*) parseFromInputStream:(NSInputStream*) input;
+ (Message_Info*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_Info*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_Info*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_Info_Builder : PBGeneratedMessage_Builder {
@private
  Message_Info* result;
}

- (Message_Info*) defaultInstance;

- (Message_Info_Builder*) clear;
- (Message_Info_Builder*) clone;

- (Message_Info*) build;
- (Message_Info*) buildPartial;

- (Message_Info_Builder*) mergeFrom:(Message_Info*) other;
- (Message_Info_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_Info_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMessageId;
- (int32_t) messageId;
- (Message_Info_Builder*) setMessageId:(int32_t) value;
- (Message_Info_Builder*) clearMessageId;

- (BOOL) hasSenderId;
- (int32_t) senderId;
- (Message_Info_Builder*) setSenderId:(int32_t) value;
- (Message_Info_Builder*) clearSenderId;

- (BOOL) hasRecipientId;
- (int32_t) recipientId;
- (Message_Info_Builder*) setRecipientId:(int32_t) value;
- (Message_Info_Builder*) clearRecipientId;

- (BOOL) hasType;
- (int32_t) type;
- (Message_Info_Builder*) setType:(int32_t) value;
- (Message_Info_Builder*) clearType;

- (BOOL) hasContent;
- (NSString*) content;
- (Message_Info_Builder*) setContent:(NSString*) value;
- (Message_Info_Builder*) clearContent;

- (BOOL) hasTitle;
- (NSString*) title;
- (Message_Info_Builder*) setTitle:(NSString*) value;
- (Message_Info_Builder*) clearTitle;

- (BOOL) hasFileId;
- (int32_t) fileId;
- (Message_Info_Builder*) setFileId:(int32_t) value;
- (Message_Info_Builder*) clearFileId;

- (BOOL) hasRoomId;
- (int32_t) roomId;
- (Message_Info_Builder*) setRoomId:(int32_t) value;
- (Message_Info_Builder*) clearRoomId;

- (BOOL) hasTime;
- (NSString*) time;
- (Message_Info_Builder*) setTime:(NSString*) value;
- (Message_Info_Builder*) clearTime;
@end

