// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "RoomData.pb.h"

@class Address;
@class Address_Builder;
@class RoomInfo;
@class RoomInfo_Builder;

@interface RoomResponseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

